### PR TITLE
Adjusted app templates for intelligent-container branch in core

### PR DESCRIPTION
**Pull request by Raydiation**
Easier template for https://github.com/owncloud/core/issues/12829

### CODE REVIEW

**Comment by LukasReschke** [comment]
Tests are failing.

**Comment by Raydiation** [comment]
@LukasReschke they ran against an old branch of master. I'll merge it into master and check if the it works, otherwise create a fix.

**Comment by LukasReschke** [comment]
Do we have documentation on that?

**Comment by Raydiation** [comment]
@LukasReschke on what? intelligent container? http://doc.owncloud.org/server/8.0/developer_manual/app/container.html#use-automatic-dependency-assembly-recommended

Problem was an apt-get upgrade btw, travis build is fixed

**Comment by LukasReschke** [comment]
THX

**Pull request merged**
