### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by chludwig**
No sudo needed for Windows

### CODE REVIEW

**Comment by BernhardPosselt** [comment]
Sure, but what about Linux and MacOS :) ?

**Comment by chludwig** [comment]
Sorry, sorry, but I am still in love with my Windows workstation and laptop, using Ubuntu as a local dev webserver that mounts my workspace (my personal way to 'vagrant' ;-).

**Comment by BernhardPosselt** [comment]
What I meant: we should add your suggestion in addition to the Mac and Linux instructions ;)

**Comment by BernhardPosselt** [comment]
Not replace them

**Comment by BernhardPosselt** [comment]
Another thing in case you did not know: owncloud 8 and higher does not run on windows

**Comment by chludwig** [comment]
I know that ownCloud is not running on windows machines, but there are still many developers working on Windows, using i. e. a Vagrant Linux box to run ownCloud Server.
I removed the 'sudo' only in the description for Windows, in the Linux description it is still there.

**Comment by BernhardPosselt** [comment]
Ah, my bad :)

The diff was showing too little

**Pull request merged**
